// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHtcnJgNjMdxtsRtzNVdm3ylByz2-dmMM',
    appId: '1:1007902368110:web:0ffc6b730acb6797de217f',
    messagingSenderId: '1007902368110',
    projectId: 'welcomeback-8e52b',
    authDomain: 'welcomeback-8e52b.firebaseapp.com',
    storageBucket: 'welcomeback-8e52b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk7vmjhmO2LoA-auUvb33hvcIheY7picw',
    appId: '1:1007902368110:android:9044a1c955462b34de217f',
    messagingSenderId: '1007902368110',
    projectId: 'welcomeback-8e52b',
    storageBucket: 'welcomeback-8e52b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-V-NEHsHdPW7zmlRUgDO_Xxe-5DB_lmo',
    appId: '1:1007902368110:ios:5c923d2a98edca75de217f',
    messagingSenderId: '1007902368110',
    projectId: 'welcomeback-8e52b',
    storageBucket: 'welcomeback-8e52b.appspot.com',
    iosBundleId: 'com.example.welcomeback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-V-NEHsHdPW7zmlRUgDO_Xxe-5DB_lmo',
    appId: '1:1007902368110:ios:3ab6057cc2104808de217f',
    messagingSenderId: '1007902368110',
    projectId: 'welcomeback-8e52b',
    storageBucket: 'welcomeback-8e52b.appspot.com',
    iosBundleId: 'com.example.welcomeback.RunnerTests',
  );
}
